include /home/lenique/.cache/wal/colors-kitty.conf
# Шрифт
font_family      DejaVuSansMono
font_size        12

# Прозрачность и размытие
background_opacity 0.6
dynamic_background_opacity yes

# Отключение мигающего курсора
cursor_blink_interval 0

# Скроллбэк (история)
scrollback_lines 10000

# Отключение звуков
enable_audio_bell no

# Отключение подтверждения закрытия окна
confirm_os_window_close 0
